# Komorebi
# A warm, eye-friendly light theme for kitty

foreground               #616161
background               #fffcf4
selection_foreground     #616161
selection_background     #e8dfc4

cursor                   #616161
cursor_text_color        #00a970

url_color                #16825d

active_tab_foreground    #616161
active_tab_background    #a4d99f
inactive_tab_foreground  #616161
inactive_tab_background  #fffcf4

active_border_color      #16825d
inactive_border_color    #f3f3f3

wayland_titlebar_color   system
macos_titlebar_color     system

# black
color0   #000000
color8   #666666

# red
color1   #cd3131
color9   #cd3131

# green
color2   #00bc00
color10  #14ce14

# yellow
color3   #949800
color11  #b5ba00

# blue
color4   #0451a5
color12  #0451a5

# magenta
color5   #bc05bc
color13  #bc05bc

# cyan
color6   #0598bc
color14  #0598bc

# white
color7   #d5cec4
color15  #f0ece4
