# Relax Light
# A warm, eye-friendly light theme for kitty

foreground               #657b83
background               #fffcf4
selection_foreground     #657b83
selection_background     #bcd68d

cursor                   #9f9371
cursor_text_color        #fffcf4

url_color                #4078F2

active_tab_foreground    #657b83
active_tab_background    #e8dfc4
inactive_tab_foreground  #657b83
inactive_tab_background  #f6f4ec

active_border_color      #4078F2
inactive_border_color    #cecdc2

wayland_titlebar_color   system
macos_titlebar_color     system

# black
color0   #000000
color8   #93a1a1

# red
color1   #E45649
color9   #CA1243

# green
color2   #50A14F
color10  #019875

# yellow
color3   #C18401
color11  #D47500

# blue
color4   #4078F2
color12  #3873ca

# magenta
color5   #A626A4
color13  #BF6EE0

# cyan
color6   #11C4C6
color14  #0598bc

# white
color7   #d5cec4
color15  #f0ece4
