# Relax Dark
# A comfortable dark theme for kitty

foreground               #abb2bf
background               #282c34
selection_foreground     #abb2bf
selection_background     #677696

cursor                   #528bff
cursor_text_color        #ffffffc9

url_color                #61afef

active_tab_foreground    #dcdcdc
active_tab_background    #282c34
inactive_tab_foreground  #9da5b4
inactive_tab_background  #21252b

active_border_color      #528bff
inactive_border_color    #181a1f

wayland_titlebar_color   system
macos_titlebar_color     system

# black
color0   #2d3139
color8   #7f848e

# red
color1   #e06c75
color9   #f44747

# green
color2   #98c379
color10  #98c379

# yellow
color3   #e5c07b
color11  #e5c07b

# blue
color4   #61afef
color12  #528bff

# magenta
color5   #c678dd
color13  #7e0097

# cyan
color6   #56b6c2
color14  #56b6c2

# white
color7   #d7dae0
color15  #d7dae0
